# Generated by Django 3.0.7 on 2020-06-22 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=150, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('content', models.CharField(max_length=2000, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateField()),
                ('eventName', models.CharField(max_length=150)),
            ],
        ),
    ]
